openapi: 3.1.0
info:
  title: Physical AI Textbook - Users API
  version: 1.0.0
  description: User profile and background management

servers:
  - url: https://api.physicalai-textbook.com/v1
    description: Production
  - url: http://localhost:8000/v1
    description: Development

paths:
  /users/me:
    get:
      summary: Get current user profile
      operationId: getCurrentUser
      tags: [Users]
      security:
        - sessionAuth: []
      responses:
        '200':
          description: User profile
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
        '401':
          description: Not authenticated

    patch:
      summary: Update current user profile
      operationId: updateCurrentUser
      tags: [Users]
      security:
        - sessionAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateProfileRequest'
      responses:
        '200':
          description: Profile updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
        '400':
          description: Invalid input
        '401':
          description: Not authenticated

    delete:
      summary: Delete current user account
      operationId: deleteCurrentUser
      tags: [Users]
      security:
        - sessionAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [confirmPassword]
              properties:
                confirmPassword:
                  type: string
      responses:
        '204':
          description: Account deleted
        '401':
          description: Not authenticated or wrong password

  /users/me/background:
    get:
      summary: Get user background assessment
      operationId: getBackground
      tags: [Users]
      security:
        - sessionAuth: []
      responses:
        '200':
          description: Background assessment data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BackgroundAssessment'
        '401':
          description: Not authenticated

    put:
      summary: Update background assessment
      operationId: updateBackground
      tags: [Users]
      security:
        - sessionAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BackgroundAssessment'
      responses:
        '200':
          description: Background updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BackgroundAssessment'
        '400':
          description: Invalid input
        '401':
          description: Not authenticated

  /users/me/preferences:
    patch:
      summary: Update user preferences
      operationId: updatePreferences
      tags: [Users]
      security:
        - sessionAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserPreferences'
      responses:
        '200':
          description: Preferences updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserPreferences'
        '400':
          description: Invalid input
        '401':
          description: Not authenticated

components:
  securitySchemes:
    sessionAuth:
      type: apiKey
      in: cookie
      name: session

  schemas:
    UserProfile:
      type: object
      properties:
        id:
          type: string
          format: uuid
        email:
          type: string
          format: email
        displayName:
          type: string
          nullable: true
        emailVerified:
          type: boolean
        background:
          $ref: '#/components/schemas/BackgroundAssessment'
        languagePreference:
          type: string
          enum: [en, ur]
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    UpdateProfileRequest:
      type: object
      properties:
        displayName:
          type: string
          maxLength: 100
          nullable: true

    BackgroundAssessment:
      type: object
      properties:
        pythonLevel:
          type: string
          enum: [beginner, intermediate, advanced]
          description: Self-reported Python proficiency
        rosExperience:
          type: string
          enum: [none, basic, experienced]
          description: Prior ROS/ROS 2 experience
        hardwareAccess:
          type: string
          enum: [simulation_only, jetson, full_kit]
          description: Available hardware for exercises
        learningGoals:
          type: array
          items:
            type: string
            enum: [ros2, simulation, isaac, vla, capstone]
          description: What modules user wants to focus on
        completedAssessment:
          type: boolean
          description: Whether user has completed full assessment
      example:
        pythonLevel: intermediate
        rosExperience: none
        hardwareAccess: simulation_only
        learningGoals: [ros2, simulation, capstone]
        completedAssessment: true

    UserPreferences:
      type: object
      properties:
        languagePreference:
          type: string
          enum: [en, ur]
          description: Content language preference
        emailNotifications:
          type: boolean
          description: Receive email notifications
        darkMode:
          type: boolean
          nullable: true
          description: UI theme preference (null = system)

    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
